version: '3.8'

services:
  server:
    container_name: node_rest_server_1
    build: .
    ports:
      - ${PORT}:${PORT}
    env_file: 
      - .env
    depends_on:
      - db
    environment:
      DB_HOST: host.docker.internal
    networks:
      - custom-net
    restart: always

    volumes:
      - .:/app/logs
      - .:/app/
  db:
    image: postgres:13.3-alpine
    env_file:
      - .env
    ports:
      - ${POSTGRESS_PORT}:${POSTGRESS_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - custom-net
    volumes:
      - ./db-data:/var/lib/postgresql/data

networks:
  custom-net:
    driver: bridge

